language: java
dist: trusty
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14
  - openjdk15

script:
  - mvn clean install -Pskip-default-test -Pintegration-test

matrix:
  fast_finish: true

branches:
  only:
    - master

after_success:
  - mvn jacoco:report coveralls:report

notifications:
  email: false


