language: java
jdk:
  - openjdk8

# Cache Maven dependencies to speed up builds
cache:
  directories:
    - $HOME/.m2

# Before the build, make the Maven wrapper script executable
before_install:
  - chmod +x mvnw

# Run the Maven build and tests
script:
  - ./mvnw clean install

